### ISSUE TITLE
Add the ability to treat certain 4## responses as success based on request URL (NEST-499)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/Orchard-Azure-Application-Insights#75]
~Browsers by default try to fetch the favicon at the /favicon.ico URL at beginning of opening a site/page, resulting in a 404 logged by AI. When the actual page is loaded, the favicon is correctly picked up based on what's defined in the corresponding head link tag. Let's ignore these initial 404 entries.~

- Add a new setting to `ApplicationInsightsOptions` that can be a regex.
- Use this regex in a new `ITelemetryProcessor` implementation to match request URLs with a 4## response and treat them as success, instead of failure.
- Use this in DotNest Tenants Core for the `/favicon.ico` and `/_MediaTheme/Templates` URLs.
- Add this regex as an example to the Readme.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-499)

**Comment by Piedone** [comment]
Since it's application-specific whether there is supposed to be anything under /favicon.ico, while this is a generally useful feature, it should be optional, and off by default to make sure you're not missing actual errors.

**Comment by BenedekFarkas** [comment]
Agreed. Is there a formal way of defining such configuration entries?

**Comment by Piedone** [comment]
We use [`ApplicationInsightsOptions`](https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/dev/Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs) for this.

**Comment by BenedekFarkas** [comment]
Oh I see, so it's entirely up to the app's configuration! I'll shuffle the issues around then. :)

**Comment by BenedekFarkas** [comment]
I just realized I misunderstood the purpose of ApplicationInsightsOptions. I imagine the ideal solution here would be to be able configure any number of such rules in our own applications and ignoring /favicon.ico 404s would just be one of them, also serving as an example described this module Readme. So such rules currently need to be wired in or is there a mechanism to define these on a case-by-case basis?

**Comment by Piedone** [comment]
Currently, you can do this from the outside with an `ITelemetryProcessor`; the full configurability of the AI .NET library is still available. So adding such a favicon ignore is also possible, but needs coding.

We could potentially have a generalization of this to allow simpler ignore rules (like with a matching URL regex) via `ApplicationInsightsOptions` instead of having to add a class. For our own sites, ignoring /favicon.ico would be useful, and on DotNest perhaps Media 404s too. However, these aren't all necessarily as simple as ignoring a piece of telemetry based on a string match, see [`TelemetryFilter`](https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/dev/Lombiq.Hosting.Azure.ApplicationInsights/Services/TelemetryFilter.cs) here and our [Media Theme-ignoring filter in DotNest](https://github.com/Lombiq/DotNest-Tenants-Core/blob/dev/src/Modules/DotNest.Hosting.Tenants/Services/MediaThemeTelemetryFilter.cs).

**Comment by BenedekFarkas** [comment]
Yeah, it would be really cool to be able to do such filtering with just configuration strings, without additional coding. Such a logic should be able to dynamically access properties by name and either use a "dictionary" of regexes (key: property name, value: filter expression), but that's both a blessing and a curse; or something like the [VSTest case filter patterns](https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests), which is defined in https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.Common/Filtering/Condition.cs, so we could build on top of that - rough example: `RequestUrlPath=/favicon.ico|ResponseCode=404` and multiple of these could be defined separated by `;`.
But the [Media Theme-ignoring filter in DotNest](https://github.com/Lombiq/DotNest-Tenants-Core/blob/dev/src/Modules/DotNest.Hosting.Tenants/Services/MediaThemeTelemetryFilter.cs) has more complex logic than what could be achieved with this.

**Comment by Piedone** [comment]
At that point, when anything more than something trivial is needed, you're better off with a custom `ITelemetryProcessor`. I wouldn't implement such a parsed configuration.

First, let's see if we can ignore 404s matching a configurable regex here, with the default being no configuration (i.e. no filtering). So we'll have something more generic than just ignoring "/favicon.ico" but we won't get carried away too much.

**Comment by Piedone** [comment]
At that point, when anything more than something trivial is needed, you're better off with a custom `ITelemetryProcessor`. I wouldn't implement such a parsed configuration.

First, let's see if we can ignore 404s matching a configurable regex here, with the default being no configuration (i.e. no filtering). So we'll have something more generic than just ignoring "/favicon.ico" but we won't get carried away too much.

**Comment by BenedekFarkas** [comment]
You mean a new setting in `ApplicationInsightsOptions` (empty by default) for a regex specifically for 404s that will be matched against the request URL path, right?

**Comment by Piedone** [comment]
Yep. I'm pretty sure that for requests like favicons, robots.txt, and cracking attempts it would work just by ignoring the request. For Media 404s I'm not sure, because there are also Blob Storage operations.

Also, even better would be not to completely ignore the request telemetry, just somehow make it that it doesn't show up under Failures... Because we need to know that these requests happen (like to be able to reject them in Cloudflare if we want, and to understand the performance impact, see them in the request/s numbers...) just we don't want them to show up as errors. I don't know if this is possible.

**Comment by wAsnk** [comment]
You can modify the telemetry in an ITelemetryInitializer to set it as a non failure, like in [the example here.](https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling?tabs=javascriptwebsdkloaderscript#addmodify-properties-itelemetryinitializer)

**Comment by Piedone** [comment]
Ah awesome, that's what we need! So, an IgnoreFailure feature that sets matching telemetry as success.

**Comment by wAsnk** [comment]
1. Should that match all 400s like in the example (code >= 400 && code < 500)? Or should we only target 404s for favicon and media?
2. Also should we add a custom property so we can filter them like in the example?

**Comment by Piedone** [comment]
1. We should match all 4xx, yeah, good idea. Not 5xx though, those are errors that always need attention.
2. Yep.
3. Also, for the existing filter in the project and the one in DotNest, we should also use `IgnoreFailure` instead of not sending the telemetry.

**Comment by wAsnk** [comment]
Alright, understood! Then I'll start this.

**Comment by Piedone** [comment]
Do note that we're talking about a configurable match for 4xxx requests; by default, these requests should be recorded as they are today.

**Comment by BenedekFarkas** [comment]
Thanks, this sounds great, updated the description to match the final scope.

**Comment by wAsnk** [comment]
By configurable do you mean a boolean or exactly specified 4xx error(s)?

**Comment by BenedekFarkas** [comment]
The URLs need to be configured, see the description.

**Comment by wAsnk** [comment]
> Use this regex in a new ITelemetryProcessor implementation to match request URLs with a 4## response and treat them as success, instead of failure.

Do you mean `ITelemetryInitializer`?
I'm not sure if I understand this regex. Is this a single configuration variable that would contain multiple URLs, or is this an array of regexes?

**Comment by Piedone** [comment]
A single regex would be OK, since that can match any number of URLs. Simple lists of configuration items without keys are not cascading among configuration sources, right? So, we couldn't define a regex in appsettings.json, and add to this list (as opposed to overwriting it) from appsettings.Production.json, for example. Because if that would work, then I'd see a point of having a list.

**Comment by Piedone** [comment]
So are lists cascading, @wAsnk?

**Comment by wAsnk** [comment]
Regex seemed to be better to use, so I didn't check that. 
Any key not overwritten remains from the previously loaded configuration. So:
```json
{ 
    "Array": [
        "FirstUrl",
        "SecondUrl"
    ]
}
```

then
```json
{ 
    "Array": [
        "NewUrl"
    ]
}
```

Would have the result:
"NewUrl", "SecondUrl"

So only the value with the same key will be overwritten, not the whole array.

**Comment by Piedone** [comment]
I'm referring to an array of regexes.

OK, this is not really intuitive nor too useful, so let's leave it how we have it.
