### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by devlife** [Lombiq/Orchard-Azure-Application-Insights#9]
I have the latest nuget package versions for all of the referenced Application Insights packages but I'm seeing a lot of missing data in app insights in the Azure portal.

Here are a few things that I'm noticing:

Here you can see that I have no operations listed:
![image](https://user-images.githubusercontent.com/237369/74873341-045c1a00-532d-11ea-8f5c-48ac57cf97c0.png)

Here you can see I have no stack trace:
![image](https://user-images.githubusercontent.com/237369/74873451-35d4e580-532d-11ea-9afd-52c7e046ffe2.png)

This is on the Performance tab. You can see again there is no list of operations:
![image](https://user-images.githubusercontent.com/237369/74873493-4be2a600-532d-11ea-8804-a032765c1c78.png)

I'm hoping I just have something misconfigured but I'm definitely hoping to be able to see these details.

In addition, the Live Metrics Stream shows 
> Not available: your app is offline or using an older SDK

**Comment by Piedone** [comment]
This is definitely an issue. However, we haven't worked on updating the packages for this module and as you can see there is no guarantee that new packages are backwards compatible. If you just want to see the data and use the module then you can do that without updating the packages: what's referenced in the source works and we see all of this data. Otherwise, you're very welcome to contribute such an update (we have very limited time to allocate to this and won't work on it in the near future) and we'll review such a PR in a timely manner.

I suggest you first trying this locally. and see whether there is any usable AI error in the Debug output window. You can check out some other troubleshooting tips by the AI team in the docs, and and I particularly recommend [this section](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#q03). Perhaps even the Orchard logs can help, or you can see exceptions with the Debugger.

**Comment by devlife** [comment]
Oh I see. Are you saying that I should see this data if I use the package versions referenced [here](https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/packages.config)?

**Comment by Piedone** [comment]
Please use the version in the dev branch, that's kept more up to date.

**Comment by devlife** [comment]
Excellent will do. Thanks!
